name: Repo Sync

on:
  workflow_dispatch:

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: aws-samples/data-perimeter-policy-examples
        source_branch: main
        destination_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        github_token: ${{ secrets.REPO_SYNC }}
    - uses: repo-sync/pull-request@v2
      name: Debug Destination Repository
      run: echo "Destination Repository: ${{ secrets.DESTINATION_REPOSITORY }}"
      name: Create pull request
      with:
        source_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        destination_repository: ${{ secrets.DESTINATION_REPOSITORY }}
        destination_branch: main
        github_token: ${{ secrets.REPO_SYNC }}
